/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './post.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './post.component';
const styles_PostComponent:any[] = [import0.styles];
export const RenderType_PostComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_PostComponent,
  data: {}
}
);
export function View_PostComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      (l()(),import1.ɵeld(0,(null as any),(null as any),18,'div',[[
        'class',
        'item'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'ui tiny image'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),0,'img',([] as any[]),[[
        8,
        'src',
        4
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n  '])),
    (l()(),import1.ɵted((null as any),['\n  '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),10,'div',[[
        'class',
        'content'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),1,'div',[[
        'class',
        'header'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import1.ɵted((null as any),['\n    '])),
      (l()(),import1.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'description'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['\n      '])),
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import1.ɵted((null as any),['\n    '])),
    (l()(),import1.ɵted((null as any),['\n  '])),
    (l()(),import1.ɵted((null as any),['\n'])),
    (l()(),import1.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import2.PostComponent = v.component;
    const currVal_0:any = import1.ɵinlineInterpolate(1,'',co.post.image,'');
    ck(v,4,0,currVal_0);
    const currVal_1:any = co.post.title;
    ck(v,10,0,currVal_1);
    const currVal_2:any = co.post.body.slice(0,(co.limit? co.limit: co.post.body.length));
    ck(v,15,0,currVal_2);
  });
}
function View_PostComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'app-post',([] as any[]),(null as any),(null as any),(null as any),View_PostComponent_0,RenderType_PostComponent)),
    import1.ɵdid(114688,(null as any),0,import2.PostComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const PostComponentNgFactory:import1.ComponentFactory<import2.PostComponent> = import1.ɵccf('app-post',import2.PostComponent,View_PostComponent_Host_0,{post: 'post'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0L3Bvc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0L3Bvc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvZWx5c2Vrb2xrZXIvZGV2L3BlcnNvbmFsL2NoYXB0ZXItMTItZnJhbWV3b3Jrcy9hbmd1bGFyMi9zcmMvYXBwL3Bvc3QvcG9zdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0L3Bvc3QuY29tcG9uZW50LnRzLlBvc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiaXRlbVwiPlxuICA8ZGl2IGNsYXNzPVwidWkgdGlueSBpbWFnZVwiPlxuICAgIDxpbWcgc3JjPXt7cG9zdC5pbWFnZX19IC8+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwiY29udGVudFwiPlxuICAgIDxkaXYgY2xhc3M9XCJoZWFkZXJcIj57e3Bvc3QudGl0bGV9fTwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJkZXNjcmlwdGlvblwiPlxuICAgICAgPHA+e3twb3N0LmJvZHkuc2xpY2UoMCwgbGltaXQgPyBsaW1pdCA6IHBvc3QuYm9keS5sZW5ndGgpfX08L3A+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG4iLCI8YXBwLXBvc3Q+PC9hcHAtcG9zdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztNQ0FBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBa0I7TUFDaEI7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUEyQjtNQUN6QjtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMEI7SUFDdEI7TUFDTjtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXFCO01BQ25CO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBb0I7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUFvQjtNQUN4QztRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQXlCO0lBQ3ZCO0lBQUc7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUE0RDtJQUMzRDtJQUNGO0lBQ0Y7Ozs7SUFSRztJQUFMLFNBQUssU0FBTDtJQUdvQjtJQUFBO0lBRWY7SUFBQTs7Ozs7SUNQVDtnQkFBQTs7O0lBQUE7OzsifQ==
