/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './post.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './post.component';
const styles_PostComponent:any[] = [i0.styles];
export const RenderType_PostComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PostComponent,data:{}});
export function View_PostComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),18,'div',[['class',
      'item']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          3,'div',[['class','ui tiny image']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),0,'img',([] as any[]),[[8,'src',
          4]],(null as any),(null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),10,'div',[['class','content']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'div',[['class',
          'header']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['',''])),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','description']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n      '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['',''])),(_l()(),
          i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n']))],
      (null as any),(_ck,_v) => {
        var _co:i2.PostComponent = _v.component;
        const currVal_0:any = i1.ɵinlineInterpolate(1,'',_co.post.image,'');
        _ck(_v,4,0,currVal_0);
        const currVal_1:any = _co.post.title;
        _ck(_v,10,0,currVal_1);
        const currVal_2:any = (_co.post.body? _co.post.body.slice(0,(_co.limit? _co.limit: _co.post.body.length)): '');
        _ck(_v,15,0,currVal_2);
      });
}
export function View_PostComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-post',([] as any[]),
      (null as any),(null as any),(null as any),View_PostComponent_0,RenderType_PostComponent)),
      i1.ɵdid(49152,(null as any),0,i2.PostComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const PostComponentNgFactory:i1.ComponentFactory<i2.PostComponent> = i1.ɵccf('app-post',
    i2.PostComponent,View_PostComponent_Host_0,{post:'post'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0L3Bvc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0L3Bvc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvZWx5c2Vrb2xrZXIvZGV2L3BlcnNvbmFsL2NoYXB0ZXItMTItZnJhbWV3b3Jrcy9hbmd1bGFyMi9zcmMvYXBwL3Bvc3QvcG9zdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0L3Bvc3QuY29tcG9uZW50LnRzLlBvc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8ZGl2IGNsYXNzPVwiaXRlbVwiPlxuICA8ZGl2IGNsYXNzPVwidWkgdGlueSBpbWFnZVwiPlxuICAgIDxpbWcgc3JjPXt7cG9zdC5pbWFnZX19IC8+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwiY29udGVudFwiPlxuICAgIDxkaXYgY2xhc3M9XCJoZWFkZXJcIj57e3Bvc3QudGl0bGV9fTwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJkZXNjcmlwdGlvblwiPlxuICAgICAgPHA+e3sgcG9zdC5ib2R5ID8gcG9zdC5ib2R5LnNsaWNlKDAsIGxpbWl0ID8gbGltaXQgOiBwb3N0LmJvZHkubGVuZ3RoKSA6IFwiXCIgfX08L3A+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG4iLCI8YXBwLXBvc3Q+PC9hcHAtcG9zdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFrQix5Q0FDaEI7VUFBQTtVQUFBLDhCQUEyQjtNQUN6QjtVQUFBLDhEQUEwQjtVQUFBLFdBQ3RCLHlDQUNOO1VBQUE7VUFBQSw0Q0FBcUI7VUFBQSxhQUNuQjtVQUFBO01BQW9CLHdDQUFvQjtNQUN4QztVQUFBO01BQXlCLDZDQUN2QjtVQUFBO1VBQUEsOEJBQUcsd0NBQStFO2lCQUFBLDRCQUM5RTtNQUNGLHVDQUNGOzs7UUFSRztRQUFMLFdBQUssU0FBTDtRQUdvQjtRQUFBO1FBRWY7UUFBQTs7OztvQkNQVDtNQUFBO2FBQUE7Ozs7In0=
