/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './posts-list.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../post/post.component.ngfactory';
import * as i3 from '../post/post.component';
import * as i4 from '@angular/common';
import * as i5 from './posts-list.component';
import * as i6 from '../services/posts.service';
const styles_PostsListComponent:any[] = [i0.styles];
export const RenderType_PostsListComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PostsListComponent,data:{}});
function View_PostsListComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-post',[['limit',
      '200']],(null as any),(null as any),(null as any),i2.View_PostComponent_0,i2.RenderType_PostComponent)),
      i1.ɵdid(49152,(null as any),0,i3.PostComponent,([] as any[]),{post:[0,'post']},
          (null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_PostsListComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
      ['\n'])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
      ['\n'])),(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),
      ['\n\n'])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_PostsListComponent_1)),i1.ɵdid(802816,(null as any),0,i4.NgForOf,[i1.ViewContainerRef,
      i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),
      i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n']))],(_ck,
      _v) => {
    var _co:i5.PostsListComponent = _v.component;
    const currVal_0:any = _co.posts;
    _ck(_v,7,0,currVal_0);
  },(null as any));
}
export function View_PostsListComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-posts-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_PostsListComponent_0,
      RenderType_PostsListComponent)),i1.ɵdid(245760,(null as any),0,i5.PostsListComponent,
      [i6.PostsService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PostsListComponentNgFactory:i1.ComponentFactory<i5.PostsListComponent> = i1.ɵccf('app-posts-list',
    i5.PostsListComponent,View_PostsListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0cy1saXN0L3Bvc3RzLWxpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0cy1saXN0L3Bvc3RzLWxpc3QuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvZWx5c2Vrb2xrZXIvZGV2L3BlcnNvbmFsL2NoYXB0ZXItMTItZnJhbWV3b3Jrcy9hbmd1bGFyMi9zcmMvYXBwL3Bvc3RzLWxpc3QvcG9zdHMtbGlzdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0cy1saXN0L3Bvc3RzLWxpc3QuY29tcG9uZW50LnRzLlBvc3RzTGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPCEtLTxkaXYgKm5nRm9yPVwibGV0IGhlcm8gb2YgaGVyb2VzXCItLT5cbjwhLS1bY2xhc3Muc2VsZWN0ZWRdPVwiaGVybyA9PT0gc2VsZWN0ZWRIZXJvXCItLT5cbjwhLS0oY2xpY2spPVwib25TZWxlY3QoaGVybylcIj4tLT5cbjwhLS08c3BhbiBjbGFzcz1cImJhZGdlXCI+e3toZXJvLmlkfX08L3NwYW4+IHt7aGVyby5uYW1lfX0tLT5cbjwhLS08L2Rpdj4tLT5cblxuPGFwcC1wb3N0ICpuZ0Zvcj1cImxldCBwb3N0IG9mIHBvc3RzXCIgW3Bvc3RdPVwicG9zdFwiIGxpbWl0PVwiMjAwXCI+PC9hcHAtcG9zdD5cbjwhLS08ZGl2PlBvc3RzLzwvZGl2Pi0tPlxuIiwiPGFwcC1wb3N0cy1saXN0PjwvYXBwLXBvc3RzLWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNPQTtNQUFBO2FBQUE7VUFBQTtJQUFxQztJQUFyQyxXQUFxQyxTQUFyQzs7OztvQkFQQSx1Q0FDdUM7TUFBQSxTQUNRLHVDQUNmO01BQUEsU0FDMkIsdUNBQzlDO01BQUEsV0FFYjtNQUFBLG1DQUFBO3VDQUFBLHlDQUEwRTthQUFBLHdCQUNsRDs7O0lBRGQ7SUFBVixXQUFVLFNBQVY7Ozs7b0JDUEE7TUFBQTttQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
