/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './browser-transfer-state.module';
import * as i2 from './transfer-state';
export const BrowserTransferStateModuleNgFactory:i0.NgModuleFactory<i1.BrowserTransferStateModule> = i0.ɵcmf(i1.BrowserTransferStateModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,
          i2.TransferState,i1.getTransferState,([] as any[])),i0.ɵmpd(512,i1.BrowserTransferStateModule,
          i1.BrowserTransferStateModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL21vZHVsZXMvdHJhbnNmZXItc3RhdGUvYnJvd3Nlci10cmFuc2Zlci1zdGF0ZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZWx5c2Vrb2xrZXIvZGV2L3BlcnNvbmFsL2NoYXB0ZXItMTItZnJhbWV3b3Jrcy9hbmd1bGFyMi9zcmMvbW9kdWxlcy90cmFuc2Zlci1zdGF0ZS9icm93c2VyLXRyYW5zZmVyLXN0YXRlLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
