/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './server-transfer-state.module';
import * as i2 from './transfer-state';
import * as i3 from './server-transfer-state';
import * as i4 from '@angular/platform-server';
export const ServerTransferStateModuleNgFactory:i0.NgModuleFactory<i1.ServerTransferStateModule> = i0.ɵcmf(i1.ServerTransferStateModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.TransferState,i3.ServerTransferState,[i4.PlatformState,i0.RendererFactory2]),
          i0.ɵmpd(512,i1.ServerTransferStateModule,i1.ServerTransferStateModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL21vZHVsZXMvdHJhbnNmZXItc3RhdGUvc2VydmVyLXRyYW5zZmVyLXN0YXRlLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9lbHlzZWtvbGtlci9kZXYvcGVyc29uYWwvY2hhcHRlci0xMi1mcmFtZXdvcmtzL2FuZ3VsYXIyL3NyYy9tb2R1bGVzL3RyYW5zZmVyLXN0YXRlL3NlcnZlci10cmFuc2Zlci1zdGF0ZS5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
