/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './transfer-http.module';
import * as i2 from '@angular/http';
import * as i3 from './transfer-http';
import * as i4 from '../transfer-state/transfer-state';
export const TransferHttpModuleNgFactory:i0.NgModuleFactory<i1.TransferHttpModule> = i0.ɵcmf(i1.TransferHttpModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.BrowserXhr,i2.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i2.ResponseOptions,
          i2.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i2.XSRFStrategy,i2.ɵb,
          ([] as any[])),i0.ɵmpd(4608,i2.XHRBackend,i2.XHRBackend,[i2.BrowserXhr,i2.ResponseOptions,
          i2.XSRFStrategy]),i0.ɵmpd(4608,i2.RequestOptions,i2.BaseRequestOptions,([] as any[])),
          i0.ɵmpd(5120,i2.Http,i2.ɵc,[i2.XHRBackend,i2.RequestOptions]),i0.ɵmpd(4608,
              i3.TransferHttp,i3.TransferHttp,[i2.Http,i4.TransferState]),i0.ɵmpd(512,
              i2.HttpModule,i2.HttpModule,([] as any[])),i0.ɵmpd(512,i1.TransferHttpModule,
              i1.TransferHttpModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL21vZHVsZXMvdHJhbnNmZXItaHR0cC90cmFuc2Zlci1odHRwLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9lbHlzZWtvbGtlci9kZXYvcGVyc29uYWwvY2hhcHRlci0xMi1mcmFtZXdvcmtzL2FuZ3VsYXIyL3NyYy9tb2R1bGVzL3RyYW5zZmVyLWh0dHAvdHJhbnNmZXItaHR0cC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
