/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.server.module';
import * as i2 from './app/app.component';
import * as i3 from './app/post-list/post-list.component.ngfactory';
import * as i4 from './app/post-detail/post-detail.component.ngfactory';
import * as i5 from './app/app.component.ngfactory';
import * as i6 from '@angular/http';
import * as i7 from '@angular/platform-server';
import * as i8 from '@angular/common';
import * as i9 from '@angular/platform-browser';
import * as i10 from '@angular/animations/browser';
import * as i11 from '@angular/platform-browser/animations';
import * as i12 from '@angular/animations';
import * as i13 from './modules/transfer-state/transfer-state';
import * as i14 from './modules/transfer-state/server-transfer-state';
import * as i15 from './modules/transfer-http/transfer-http';
import * as i16 from '@angular/router';
import * as i17 from './app/services/comments.service';
import * as i18 from './app/services/posts.service';
import * as i19 from './modules/transfer-state/server-transfer-state.module';
import * as i20 from './modules/transfer-http/transfer-http.module';
import * as i21 from './app/post-list/post-list.component';
import * as i22 from './app/post-detail/post-detail.component';
import * as i23 from './app/app.module';
export const AppServerModuleNgFactory:i0.NgModuleFactory<i1.AppServerModule> = i0.ɵcmf(i1.AppServerModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.PostListComponentNgFactory,i4.PostDetailComponentNgFactory,i5.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i6.BrowserXhr,
          i7.ɵc,([] as any[])),i0.ɵmpd(4608,i6.ResponseOptions,i6.BaseResponseOptions,
          ([] as any[])),i0.ɵmpd(4608,i6.XSRFStrategy,i7.ɵd,([] as any[])),i0.ɵmpd(4608,
          i6.XHRBackend,i6.XHRBackend,[i6.BrowserXhr,i6.ResponseOptions,i6.XSRFStrategy]),
          i0.ɵmpd(4608,i6.RequestOptions,i6.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,
              i6.Http,i7.ɵe,[i6.XHRBackend,i6.RequestOptions]),i0.ɵmpd(5120,i0.LOCALE_ID,
              i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i8.NgLocalization,i8.NgLocaleLocalization,
              [i0.LOCALE_ID]),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i9.DomSanitizer,
              i9.ɵe,[i9.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i9.DomSanitizer]),
          i0.ɵmpd(4608,i9.HAMMER_GESTURE_CONFIG,i9.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i9.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i9.ɵDomEventsPlugin(p0_0),new i9.ɵKeyEventsPlugin(p1_0),new i9.ɵHammerGesturesPlugin(p2_0,
                p2_1)];
          },[i9.DOCUMENT,i9.DOCUMENT,i9.DOCUMENT,i9.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i9.EventManager,i9.EventManager,[i9.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i9.ɵDomSharedStylesHost,i9.ɵDomSharedStylesHost,[i9.DOCUMENT]),
          i0.ɵmpd(4608,i9.ɵDomRendererFactory2,i9.ɵDomRendererFactory2,[i9.EventManager,
              i9.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i7.ɵb,i7.ɵb,[i9.DOCUMENT,[2,i9.ɵTRANSITION_ID]]),
          i0.ɵmpd(6144,i9.ɵSharedStylesHost,(null as any),[i7.ɵb]),i0.ɵmpd(4608,i7.ɵServerRendererFactory2,
              i7.ɵServerRendererFactory2,[i0.NgZone,i9.DOCUMENT,i9.ɵSharedStylesHost]),
          i0.ɵmpd(4608,i10.AnimationDriver,i10.ɵNoopAnimationDriver,([] as any[])),
          i0.ɵmpd(5120,i10.ɵAnimationStyleNormalizer,i11.ɵd,([] as any[])),i0.ɵmpd(4608,
              i10.ɵAnimationEngine,i11.ɵb,[i10.AnimationDriver,i10.ɵAnimationStyleNormalizer]),
          i0.ɵmpd(5120,i0.RendererFactory2,i7.ɵa,[i7.ɵServerRendererFactory2,i10.ɵAnimationEngine,
              i0.NgZone]),i0.ɵmpd(4352,i0.Testability,(null as any),([] as any[])),
          i0.ɵmpd(4608,i9.Meta,i9.Meta,[i9.DOCUMENT]),i0.ɵmpd(4608,i9.Title,i9.Title,
              [i9.DOCUMENT]),i0.ɵmpd(4608,i12.AnimationBuilder,i11.ɵBrowserAnimationBuilder,
              [i0.RendererFactory2]),i0.ɵmpd(4608,i13.TransferState,i14.ServerTransferState,
              [i7.PlatformState,i0.RendererFactory2]),i0.ɵmpd(4608,i15.TransferHttp,
              i15.TransferHttp,[i6.Http,i13.TransferState]),i0.ɵmpd(5120,i16.ActivatedRoute,
              i16.ɵf,[i16.Router]),i0.ɵmpd(4608,i16.NoPreloading,i16.NoPreloading,
              ([] as any[])),i0.ɵmpd(6144,i16.PreloadingStrategy,(null as any),[i16.NoPreloading]),
          i0.ɵmpd(135680,i16.RouterPreloader,i16.RouterPreloader,[i16.Router,i0.NgModuleFactoryLoader,
              i0.Compiler,i0.Injector,i16.PreloadingStrategy]),i0.ɵmpd(4608,i16.PreloadAllModules,
              i16.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i16.ROUTER_INITIALIZER,
              i16.ɵi,[i16.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any,p1_0:any,
              p1_1:any) => {
            return [p0_0,i1.onBootstrap(p1_0,p1_1)];
          },[i16.ROUTER_INITIALIZER,i0.ApplicationRef,i13.TransferState]),i0.ɵmpd(4608,
              i17.CommentsService,i17.CommentsService,([] as any[])),i0.ɵmpd(4608,
              i18.PostsService,i18.PostsService,[i15.TransferHttp]),i0.ɵmpd(512,i6.HttpModule,
              i6.HttpModule,([] as any[])),i0.ɵmpd(512,i8.CommonModule,i8.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i9.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i16.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i16.ɵg,i16.ɵg,[i0.Injector]),i0.ɵmpd(256,
              i0.APP_ID,'ng-universal-example',([] as any[])),i0.ɵmpd(2048,i9.ɵTRANSITION_ID,
              (null as any),[i0.APP_ID]),i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,
              p0_1:any,p1_0:any,p2_0:any,p2_1:any,p2_2:any) => {
            return [i9.ɵc(p0_0,p0_1),i16.ɵh(p1_0),i9.ɵf(p2_0,p2_1,p2_2)];
          },[[2,i9.NgProbeToken],[2,i0.NgProbeToken],i16.ɵg,i9.ɵTRANSITION_ID,i9.DOCUMENT,
              i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i9.BrowserModule,
              i9.BrowserModule,[[3,i9.BrowserModule]]),i0.ɵmpd(512,i11.NoopAnimationsModule,
              i11.NoopAnimationsModule,([] as any[])),i0.ɵmpd(512,i7.ServerModule,
              i7.ServerModule,([] as any[])),i0.ɵmpd(512,i19.ServerTransferStateModule,
              i19.ServerTransferStateModule,([] as any[])),i0.ɵmpd(512,i20.TransferHttpModule,
              i20.TransferHttpModule,([] as any[])),i0.ɵmpd(1024,i16.ɵa,i16.ɵd,[[3,
              i16.Router]]),i0.ɵmpd(512,i16.UrlSerializer,i16.DefaultUrlSerializer,
              ([] as any[])),i0.ɵmpd(512,i16.ChildrenOutletContexts,i16.ChildrenOutletContexts,
              ([] as any[])),i0.ɵmpd(256,i16.ROUTER_CONFIGURATION,{},([] as any[])),
          i0.ɵmpd(1024,i8.LocationStrategy,i16.ɵc,[i8.PlatformLocation,[2,i8.APP_BASE_HREF],
              i16.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i8.Location,i8.Location,[i8.LocationStrategy]),
          i0.ɵmpd(512,i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i16.ROUTES,() => {
            return [[{path:'',component:i21.PostListComponent},{path:'post/:id',component:i22.PostDetailComponent}]];
          },([] as any[])),i0.ɵmpd(1024,i16.Router,i16.ɵe,[i0.ApplicationRef,i16.UrlSerializer,
              i16.ChildrenOutletContexts,i8.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i16.ROUTES,i16.ROUTER_CONFIGURATION,[2,i16.UrlHandlingStrategy],
              [2,i16.RouteReuseStrategy]]),i0.ɵmpd(512,i16.RouterModule,i16.RouterModule,
              [[2,i16.ɵa],[2,i16.Router]]),i0.ɵmpd(512,i23.AppModule,i23.AppModule,
              ([] as any[])),i0.ɵmpd(512,i1.AppServerModule,i1.AppServerModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC5zZXJ2ZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC5zZXJ2ZXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
