/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './browser.module';
import * as i2 from './app/app.component';
import * as i3 from './app/app.component.ngfactory';
import * as i4 from '@angular/common';
import * as i5 from '@angular/platform-browser';
import * as i6 from './modules/transfer-state/transfer-state';
import * as i7 from './modules/transfer-state/browser-transfer-state.module';
import * as i8 from '@angular/http';
import * as i9 from './modules/transfer-http/transfer-http';
import * as i10 from './app/services/comments.service';
import * as i11 from './app/services/posts.service';
import * as i12 from './modules/transfer-http/transfer-http.module';
import * as i13 from './app/app.module';
export const AppBrowserModuleNgFactory:i0.NgModuleFactory<i1.AppBrowserModule> = i0.ɵcmf(i1.AppBrowserModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i4.NgLocalization,
              i4.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i5.DomSanitizer,
              i5.ɵe,[i5.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i5.DomSanitizer]),
          i0.ɵmpd(4608,i5.HAMMER_GESTURE_CONFIG,i5.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i5.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i5.ɵDomEventsPlugin(p0_0),new i5.ɵKeyEventsPlugin(p1_0),new i5.ɵHammerGesturesPlugin(p2_0,
                p2_1)];
          },[i5.DOCUMENT,i5.DOCUMENT,i5.DOCUMENT,i5.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i5.EventManager,i5.EventManager,[i5.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i5.ɵDomSharedStylesHost,i5.ɵDomSharedStylesHost,[i5.DOCUMENT]),
          i0.ɵmpd(4608,i5.ɵDomRendererFactory2,i5.ɵDomRendererFactory2,[i5.EventManager,
              i5.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i5.ɵDomRendererFactory2]),i0.ɵmpd(6144,i5.ɵSharedStylesHost,(null as any),
              [i5.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i5.Meta,i5.Meta,[i5.DOCUMENT]),i0.ɵmpd(4608,
              i5.Title,i5.Title,[i5.DOCUMENT]),i0.ɵmpd(5120,i6.TransferState,i7.getTransferState,
              ([] as any[])),i0.ɵmpd(4608,i8.BrowserXhr,i8.BrowserXhr,([] as any[])),
          i0.ɵmpd(4608,i8.ResponseOptions,i8.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,
              i8.XSRFStrategy,i8.ɵb,([] as any[])),i0.ɵmpd(4608,i8.XHRBackend,i8.XHRBackend,
              [i8.BrowserXhr,i8.ResponseOptions,i8.XSRFStrategy]),i0.ɵmpd(4608,i8.RequestOptions,
              i8.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i8.Http,i8.ɵc,[i8.XHRBackend,
              i8.RequestOptions]),i0.ɵmpd(4608,i9.TransferHttp,i9.TransferHttp,[i8.Http,
              i6.TransferState]),i0.ɵmpd(4608,i10.CommentsService,i10.CommentsService,
              ([] as any[])),i0.ɵmpd(4608,i11.PostsService,i11.PostsService,[i9.TransferHttp]),
          i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i5.ɵa,([] as any[])),i0.ɵmpd(256,i0.APP_ID,'ng-universal-example',
              ([] as any[])),i0.ɵmpd(2048,i5.ɵTRANSITION_ID,(null as any),[i0.APP_ID]),
          i0.ɵmpd(1024,i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any,p1_1:any,p1_2:any) => {
            return [i5.ɵc(p0_0,p0_1),i5.ɵf(p1_0,p1_1,p1_2)];
          },[[2,i5.NgProbeToken],[2,i0.NgProbeToken],i5.ɵTRANSITION_ID,i5.DOCUMENT,
              i0.Injector]),i0.ɵmpd(512,i0.ApplicationInitStatus,i0.ApplicationInitStatus,
              [[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,i0.ɵe,[i0.NgZone,i0.ɵConsole,
              i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,i0.ApplicationInitStatus]),
          i0.ɵmpd(2048,i0.ApplicationRef,(null as any),[i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,
              i0.ApplicationModule,[i0.ApplicationRef]),i0.ɵmpd(512,i5.BrowserModule,
              i5.BrowserModule,[[3,i5.BrowserModule]]),i0.ɵmpd(512,i7.BrowserTransferStateModule,
              i7.BrowserTransferStateModule,([] as any[])),i0.ɵmpd(512,i8.HttpModule,
              i8.HttpModule,([] as any[])),i0.ɵmpd(512,i12.TransferHttpModule,i12.TransferHttpModule,
              ([] as any[])),i0.ɵmpd(512,i13.AppModule,i13.AppModule,([] as any[])),
          i0.ɵmpd(512,i1.AppBrowserModule,i1.AppBrowserModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2Jyb3dzZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2Jyb3dzZXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
