/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './post-list.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../post/post.component.ngfactory';
import * as i3 from '../post/post.component';
import * as i4 from '@angular/common';
import * as i5 from './post-list.component';
import * as i6 from '../services/posts.service';
const styles_PostListComponent:any[] = [i0.styles];
export const RenderType_PostListComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PostListComponent,data:{}});
function View_PostListComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-post',[['limit',
      '200']],(null as any),(null as any),(null as any),i2.View_PostComponent_0,i2.RenderType_PostComponent)),
      i1.ɵdid(49152,(null as any),0,i3.PostComponent,([] as any[]),{post:[0,'post']},
          (null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_PostListComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'ui link items']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_PostListComponent_1)),i1.ɵdid(802816,
          (null as any),0,i4.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i5.PostListComponent = _v.component;
    const currVal_0:any = _co.posts;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_PostListComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-posts-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_PostListComponent_0,
      RenderType_PostListComponent)),i1.ɵdid(245760,(null as any),0,i5.PostListComponent,
      [i6.PostsService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PostListComponentNgFactory:i1.ComponentFactory<i5.PostListComponent> = i1.ɵccf('app-posts-list',
    i5.PostListComponent,View_PostListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWxpc3QvcG9zdC1saXN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9lbHlzZWtvbGtlci9kZXYvcGVyc29uYWwvY2hhcHRlci0xMi1mcmFtZXdvcmtzL2FuZ3VsYXIyL3NyYy9hcHAvcG9zdC1saXN0L3Bvc3QtbGlzdC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9lbHlzZWtvbGtlci9kZXYvcGVyc29uYWwvY2hhcHRlci0xMi1mcmFtZXdvcmtzL2FuZ3VsYXIyL3NyYy9hcHAvcG9zdC1saXN0L3Bvc3QtbGlzdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWxpc3QvcG9zdC1saXN0LmNvbXBvbmVudC50cy5Qb3N0TGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJ1aSBsaW5rIGl0ZW1zXCI+XG4gIDxhcHAtcG9zdCAqbmdGb3I9XCJsZXQgcG9zdCBvZiBwb3N0c1wiIFtwb3N0XT1cInBvc3RcIiBsaW1pdD1cIjIwMFwiPjwvYXBwLXBvc3Q+XG48L2Rpdj5cbiIsIjxhcHAtcG9zdHMtbGlzdD48L2FwcC1wb3N0cy1saXN0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQ0U7TUFBQTthQUFBO1VBQUE7SUFBcUM7SUFBckMsV0FBcUMsU0FBckM7Ozs7b0JBREY7TUFBQTtNQUEyQix5Q0FDekI7VUFBQSxnRUFBQTtVQUFBO1VBQUEsdUNBQTBFO01BQ3RFOztJQURNO0lBQVYsV0FBVSxTQUFWOzs7O29CQ0RGO01BQUE7a0NBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
