/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './post-list.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '@angular/router';
import * as i3 from '@angular/common';
import * as i4 from '../post/post.component.ngfactory';
import * as i5 from '../post/post.component';
import * as i6 from './post-list.component';
import * as i7 from '../services/posts.service';
const styles_PostListComponent:any[] = [i0.styles];
export const RenderType_PostListComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PostListComponent,data:{}});
function View_PostListComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),8,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
      5,'a',([] as any[]),[[1,'target',0],[8,'href',4]],[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        if (('click' === en)) {
          const pd_0:any = ((<any>i1.ɵnov(_v,3).onClick($event.button,$event.ctrlKey,
              $event.metaKey,$event.shiftKey)) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),i1.ɵdid(671744,(null as any),0,i2.RouterLinkWithHref,
      [i2.Router,i2.ActivatedRoute,i3.LocationStrategy],{routerLink:[0,'routerLink']},
      (null as any)),(_l()(),i1.ɵted((null as any),['\n      '])),(_l()(),i1.ɵeld(0,
      (null as any),(null as any),1,'app-post',[['limit','200']],(null as any),(null as any),
      (null as any),i4.View_PostComponent_0,i4.RenderType_PostComponent)),i1.ɵdid(49152,
      (null as any),0,i5.PostComponent,([] as any[]),{post:[0,'post']},(null as any)),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n  ']))],
      (_ck,_v) => {
        const currVal_2:any = i1.ɵinlineInterpolate(1,'post/',_v.context.$implicit.urlSlug,
            '');
        _ck(_v,3,0,currVal_2);
        const currVal_3:any = _v.context.$implicit;
        _ck(_v,6,0,currVal_3);
      },(_ck,_v) => {
        const currVal_0:any = i1.ɵnov(_v,3).target;
        const currVal_1:any = i1.ɵnov(_v,3).href;
        _ck(_v,2,0,currVal_0,currVal_1);
      });
}
export function View_PostListComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),4,'div',[['class',
      'ui link items']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_PostListComponent_1)),i1.ɵdid(802816,
          (null as any),0,i3.NgForOf,[i1.ViewContainerRef,i1.TemplateRef,i1.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i6.PostListComponent = _v.component;
    const currVal_0:any = _co.posts;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_PostListComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-posts-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_PostListComponent_0,
      RenderType_PostListComponent)),i1.ɵdid(245760,(null as any),0,i6.PostListComponent,
      [i7.PostsService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PostListComponentNgFactory:i1.ComponentFactory<i6.PostListComponent> = i1.ɵccf('app-posts-list',
    i6.PostListComponent,View_PostListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWxpc3QvcG9zdC1saXN0LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9lbHlzZWtvbGtlci9kZXYvcGVyc29uYWwvY2hhcHRlci0xMi1mcmFtZXdvcmtzL2FuZ3VsYXIyL3NyYy9hcHAvcG9zdC1saXN0L3Bvc3QtbGlzdC5jb21wb25lbnQudHMiLCJuZzovLy9Vc2Vycy9lbHlzZWtvbGtlci9kZXYvcGVyc29uYWwvY2hhcHRlci0xMi1mcmFtZXdvcmtzL2FuZ3VsYXIyL3NyYy9hcHAvcG9zdC1saXN0L3Bvc3QtbGlzdC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWxpc3QvcG9zdC1saXN0LmNvbXBvbmVudC50cy5Qb3N0TGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJ1aSBsaW5rIGl0ZW1zXCI+XG4gIDxkaXYgKm5nRm9yPVwibGV0IHBvc3Qgb2YgcG9zdHNcIj5cbiAgICA8YSByb3V0ZXJMaW5rPVwicG9zdC97e3Bvc3QudXJsU2x1Z319XCI+XG4gICAgICA8YXBwLXBvc3QgW3Bvc3RdPVwicG9zdFwiIGxpbWl0PVwiMjAwXCIgPjwvYXBwLXBvc3Q+XG4gICAgPC9hPlxuICA8L2Rpdj5cbjwvZGl2PlxuIiwiPGFwcC1wb3N0cy1saXN0PjwvYXBwLXBvc3RzLWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQ0U7TUFBQSx3RUFBZ0M7YUFBQSw0QkFDOUI7TUFBQTtNQUFBO1FBQUE7UUFBQTtVQUFBO2NBQUE7VUFBQTtRQUFBO1FBQUE7TUFBQSx1Q0FBQTtNQUFBO01BQUEsZUFBc0MsNkNBQ3BDO01BQUE7TUFBQSwyRUFBQTtNQUFBO01BQWdELDJDQUM5Qzs7UUFGRDtZQUFBO1FBQUgsV0FBRyxTQUFIO1FBQ1k7UUFBVixXQUFVLFNBQVY7O1FBREY7UUFBQTtRQUFBLFdBQUEsbUJBQUE7Ozs7b0JBRko7TUFBQTtNQUEyQix5Q0FDekI7VUFBQSxnRUFBQTtVQUFBO1VBQUEsdUNBSU07TUFDRjs7SUFMQztJQUFMLFdBQUssU0FBTDs7OztvQkNERjtNQUFBO2tDQUFBLFVBQUE7TUFBQTtJQUFBOzs7OyJ9
