/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './post-detail.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './post-detail.component';
const styles_PostDetailComponent:any[] = [i0.styles];
export const RenderType_PostDetailComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PostDetailComponent,data:{}});
export function View_PostDetailComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),12,'div',[['class',
      'ui main text container offset']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),2,'div',[['class','ui segment items']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          5,'div',[['class','ui comments']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h3',[['class','ui dividing header']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['Comments'])),(_l()(),i1.ɵted((null as any),['\n    '])),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(null as any),(null as any));
}
export function View_PostDetailComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-post-detail',
      ([] as any[]),(null as any),(null as any),(null as any),View_PostDetailComponent_0,
      RenderType_PostDetailComponent)),i1.ɵdid(114688,(null as any),0,i2.PostDetailComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const PostDetailComponentNgFactory:i1.ComponentFactory<i2.PostDetailComponent> = i1.ɵccf('app-post-detail',
    i2.PostDetailComponent,View_PostDetailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWRldGFpbC9wb3N0LWRldGFpbC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZWx5c2Vrb2xrZXIvZGV2L3BlcnNvbmFsL2NoYXB0ZXItMTItZnJhbWV3b3Jrcy9hbmd1bGFyMi9zcmMvYXBwL3Bvc3QtZGV0YWlsL3Bvc3QtZGV0YWlsLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWRldGFpbC9wb3N0LWRldGFpbC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWRldGFpbC9wb3N0LWRldGFpbC5jb21wb25lbnQudHMuUG9zdERldGFpbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJ1aSBtYWluIHRleHQgY29udGFpbmVyIG9mZnNldFwiPlxuICA8ZGl2IGNsYXNzPVwidWkgc2VnbWVudCBpdGVtc1wiPlxuICAgIDwhLS08UG9zdCB7Li4ucHJvcHMucG9zdH0gLz4tLT5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJ1aSBjb21tZW50c1wiPlxuICAgIDxoMyBjbGFzcz1cInVpIGRpdmlkaW5nIGhlYWRlclwiPkNvbW1lbnRzPC9oMz5cbiAgICA8IS0teyBjb21tZW50cyhwcm9wcy5jb21tZW50cykgfS0tPlxuICA8L2Rpdj5cbjwvZGl2PlxuIiwiPGFwcC1wb3N0LWRldGFpbD48L2FwcC1wb3N0LWRldGFpbD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTtNQUFBLDhCQUEyQyx5Q0FDekM7YUFBQTtVQUFBO01BQThCLDJDQUNHO01BQzNCLHlDQUNOO1VBQUE7VUFBQSw4QkFBeUI7TUFDdkI7VUFBQTtNQUErQiw2Q0FBYTtNQUNULHlDQUMvQjtNQUNGOzs7b0JDUk47TUFBQTtvQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
