/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './post-detail.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from '../comment/comment.component.ngfactory';
import * as i3 from '../comment/comment.component';
import * as i4 from '../post/post.component.ngfactory';
import * as i5 from '../post/post.component';
import * as i6 from '@angular/common';
import * as i7 from './post-detail.component';
import * as i8 from '../services/comments.service';
import * as i9 from '../services/posts.service';
import * as i10 from '@angular/router';
const styles_PostDetailComponent:any[] = [i0.styles];
export const RenderType_PostDetailComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_PostDetailComponent,data:{}});
function View_PostDetailComponent_1(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-comment',
      ([] as any[]),(null as any),(null as any),(null as any),i2.View_CommentComponent_0,
      i2.RenderType_CommentComponent)),i1.ɵdid(114688,(null as any),0,i3.CommentComponent,
      ([] as any[]),{comment:[0,'comment']},(null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_PostDetailComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),16,'div',[['class',
      'ui main text container offset']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),4,'div',[['class','ui segment items']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i1.ɵted((null as any),['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),
          1,'app-post',([] as any[]),(null as any),(null as any),(null as any),i4.View_PostComponent_0,
          i4.RenderType_PostComponent)),i1.ɵdid(49152,(null as any),0,i5.PostComponent,
          ([] as any[]),{post:[0,'post']},(null as any)),(_l()(),i1.ɵted((null as any),
          ['\n  '])),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵeld(0,(null as any),
          (null as any),7,'div',[['class','ui comments']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'h3',[['class',
          'ui dividing header']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i1.ɵted((null as any),['Comments'])),(_l()(),i1.ɵted((null as any),
          ['\n    '])),(_l()(),i1.ɵand(16777216,(null as any),(null as any),1,(null as any),
          View_PostDetailComponent_1)),i1.ɵdid(802816,(null as any),0,i6.NgForOf,[i1.ViewContainerRef,
          i1.TemplateRef,i1.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),
      (_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),i1.ɵted((null as any),['\n'])),
      (_l()(),i1.ɵted((null as any),['\n']))],(_ck,_v) => {
    var _co:i7.PostDetailComponent = _v.component;
    const currVal_0:any = _co.post;
    _ck(_v,5,0,currVal_0);
    const currVal_1:any = _co.comments;
    _ck(_v,14,0,currVal_1);
  },(null as any));
}
export function View_PostDetailComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-post-detail',
      ([] as any[]),(null as any),(null as any),(null as any),View_PostDetailComponent_0,
      RenderType_PostDetailComponent)),i1.ɵdid(245760,(null as any),0,i7.PostDetailComponent,
      [i8.CommentsService,i9.PostsService,i10.ActivatedRoute],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export const PostDetailComponentNgFactory:i1.ComponentFactory<i7.PostDetailComponent> = i1.ɵccf('app-post-detail',
    i7.PostDetailComponent,View_PostDetailComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWRldGFpbC9wb3N0LWRldGFpbC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZWx5c2Vrb2xrZXIvZGV2L3BlcnNvbmFsL2NoYXB0ZXItMTItZnJhbWV3b3Jrcy9hbmd1bGFyMi9zcmMvYXBwL3Bvc3QtZGV0YWlsL3Bvc3QtZGV0YWlsLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWRldGFpbC9wb3N0LWRldGFpbC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2VseXNla29sa2VyL2Rldi9wZXJzb25hbC9jaGFwdGVyLTEyLWZyYW1ld29ya3MvYW5ndWxhcjIvc3JjL2FwcC9wb3N0LWRldGFpbC9wb3N0LWRldGFpbC5jb21wb25lbnQudHMuUG9zdERldGFpbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJ1aSBtYWluIHRleHQgY29udGFpbmVyIG9mZnNldFwiPlxuICA8ZGl2IGNsYXNzPVwidWkgc2VnbWVudCBpdGVtc1wiPlxuICAgIDxhcHAtcG9zdCBbcG9zdF09XCJwb3N0XCI+PC9hcHAtcG9zdD5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJ1aSBjb21tZW50c1wiPlxuICAgIDxoMyBjbGFzcz1cInVpIGRpdmlkaW5nIGhlYWRlclwiPkNvbW1lbnRzPC9oMz5cbiAgICA8YXBwLWNvbW1lbnQgKm5nRm9yPVwibGV0IGNvbW1lbnQgb2YgY29tbWVudHNcIiBbY29tbWVudF09XCJjb21tZW50XCI+PC9hcHAtY29tbWVudD5cbiAgPC9kaXY+XG48L2Rpdj5cbiIsIjxhcHAtcG9zdC1kZXRhaWw+PC9hcHAtcG9zdC1kZXRhaWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDTUk7TUFBQTtvQ0FBQSxVQUFBO01BQUE7SUFBOEM7SUFBOUMsV0FBOEMsU0FBOUM7Ozs7b0JBTko7TUFBQTtNQUFBLDhCQUEyQyx5Q0FDekM7YUFBQTtVQUFBO01BQThCLDJDQUM1QjtVQUFBO3FDQUFBLFVBQUE7VUFBQSwrQ0FBbUM7VUFBQSxXQUMvQix5Q0FDTjtVQUFBO1VBQUEsNENBQXlCO1VBQUEsYUFDdkI7VUFBQTtVQUFBLGdCQUErQiw2Q0FBYTtVQUFBLGFBQzVDO1VBQUEsb0NBQUE7MkNBQUE7TUFBZ0YseUNBQzVFO01BQ0Y7O0lBTlE7SUFBVixXQUFVLFNBQVY7SUFJYTtJQUFiLFlBQWEsU0FBYjs7OztvQkNOSjtNQUFBO29DQUFBLFVBQUE7TUFBQTs7UUFBQTs7OzsifQ==
